version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www
    environment:
      APP_ENV: local
      APP_DEBUG: true
      DB_CONNECTION: sqlite
      DB_DATABASE: database/database.sqlite
    command: |
      sh -c "
        php artisan migrate:fresh --seed &&
        php artisan serve --host=0.0.0.0 --port=8000
      "
    working_dir: /var/www
