<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HomeController; // For main page and contact
use App\Http\Controllers\Teacher\SubjectController as TeacherSubjectController;
use App\Http\Controllers\Teacher\TaskController as TeacherTaskController;
use App\Http\Controllers\Teacher\SolutionController as TeacherSolutionController;
use App\Http\Controllers\Student\SubjectController as StudentSubjectController;
use App\Http\Controllers\Student\TaskController as StudentTaskController;
use App\Http\Controllers\AboutController;

/*
|--------------------------------------------------------------------------
| Public Routes
|--------------------------------------------------------------------------
*/
Route::get('/', [HomeController::class, 'index'])->name('home');
Route::get('/about', [AboutController::class, 'index'])->name('about');
Route::get('/contact', [HomeController::class, 'contact'])->name('contact');
Route::get('/privacy', function () {
    return view('privacy');
})->name('privacy');

Route::get('/dashboard', function () {
    if (auth()->check()) {
        if (auth()->user()->is_teacher) {
            // Redirect teachers to their subjects index
            return redirect()->route('teacher.subjects.index');
        } else {
            // Redirect students to their subject index
            return redirect()->route('student.subjects.index');
        }
    }
    return redirect('/');
})->middleware(['auth'])->name('dashboard');


// Authentication routes are generated by Breeze automatically
require __DIR__.'/auth.php';

/*
|--------------------------------------------------------------------------
| Teacher Routes (Protected)
|--------------------------------------------------------------------------
*/
Route::middleware(['auth', 'teacher'])->prefix('teacher')->name('teacher.')->group(function () {
    // Subject routes
    Route::get('subjects', [TeacherSubjectController::class, 'index'])->name('subjects.index');
    Route::get('subjects/create', [TeacherSubjectController::class, 'create'])->name('subjects.create');
    Route::post('subjects', [TeacherSubjectController::class, 'store'])->name('subjects.store');
    Route::get('subjects/{subject}', [TeacherSubjectController::class, 'show'])->name('subjects.show');
    Route::get('subjects/{subject}/edit', [TeacherSubjectController::class, 'edit'])->name('subjects.edit');
    Route::put('subjects/{subject}', [TeacherSubjectController::class, 'update'])->name('subjects.update');
    Route::delete('subjects/{subject}', [TeacherSubjectController::class, 'destroy'])->name('subjects.destroy');

    // Task routes (tasks are always linked to a subject)
    Route::get('subjects/{subject}/tasks/create', [TeacherTaskController::class, 'create'])->name('tasks.create');
    Route::post('subjects/{subject}/tasks', [TeacherTaskController::class, 'store'])->name('tasks.store');
    Route::get('tasks/{task}', [TeacherTaskController::class, 'show'])->name('tasks.show');
    Route::get('tasks/{task}/edit', [TeacherTaskController::class, 'edit'])->name('tasks.edit');
    Route::put('tasks/{task}', [TeacherTaskController::class, 'update'])->name('tasks.update');

    // Evaluate solution routes
    Route::get('solutions/{solution}/evaluate', [TeacherSolutionController::class, 'edit'])->name('solutions.edit');
    Route::put('solutions/{solution}/evaluate', [TeacherSolutionController::class, 'update'])->name('solutions.update');
});

/*
|--------------------------------------------------------------------------
| Student Routes (Protected)
|--------------------------------------------------------------------------
*/
Route::middleware(['auth', 'student'])->prefix('student')->name('student.')->group(function () {
    // Subject routes
    Route::get('subjects', [StudentSubjectController::class, 'index'])->name('subjects.index');
    Route::post('subjects/{subject}/leave', [StudentSubjectController::class, 'leave'])->name('subjects.leave');
    Route::get('subjects/take', [StudentSubjectController::class, 'showAvailableSubjects'])->name('subjects.take');
    Route::post('subjects/{subject}/take', [StudentSubjectController::class, 'take'])->name('subjects.doTake');
    Route::get('subjects/{subject}', [StudentSubjectController::class, 'show'])->name('subjects.show');

    // Task routes for student submission
    Route::get('tasks/{task}', [StudentTaskController::class, 'show'])->name('tasks.show');
    Route::post('tasks/{task}/submit', [StudentTaskController::class, 'submitSolution'])->name('tasks.submit');
});
